### Houseprices Linear Rgeression

##### Use this dataset on house price prediction in kaggle, perform EDA on it and then predict the house prices using linear regression.   
You can drop the categorical features and the date columns. Then try ElasticNetCV and RidgeCV on the same dataset.   
Record the scores in a dataframe with the columns mae, mse, rmse so you can compare the models.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv("../../data/house_prices.csv") #relative path

df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [2]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [3]:
df.info() # datatype 'object' => categorical features => diskreta värden som inte är kategoriska. Kan vara numeriska

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           4600 non-null   object 
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64  
 5   sqft_lot       4600 non-null   int64  
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64  
 8   view           4600 non-null   int64  
 9   condition      4600 non-null   int64  
 10  sqft_above     4600 non-null   int64  
 11  sqft_basement  4600 non-null   int64  
 12  yr_built       4600 non-null   int64  
 13  yr_renovated   4600 non-null   int64  
 14  street         4600 non-null   object 
 15  city           4600 non-null   object 
 16  statezip       4600 non-null   object 
 17  country        4600 non-null   object 
dtypes: float

In [4]:
df.describe()

price     bedrooms    bathrooms   sqft_living      sqft_lot  \
count  4.600000e+03  4600.000000  4600.000000   4600.000000  4.600000e+03   
mean   5.519630e+05     3.400870     2.160815   2139.346957  1.485252e+04   
std    5.638347e+05     0.908848     0.783781    963.206916  3.588444e+04   
min    0.000000e+00     0.000000     0.000000    370.000000  6.380000e+02   
25%    3.228750e+05     3.000000     1.750000   1460.000000  5.000750e+03   
50%    4.609435e+05     3.000000     2.250000   1980.000000  7.683000e+03   
75%    6.549625e+05     4.000000     2.500000   2620.000000  1.100125e+04   
max    2.659000e+07     9.000000     8.000000  13540.000000  1.074218e+06   

            floors   waterfront         view    condition   sqft_above  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000   
mean      1.512065     0.007174     0.240652     3.451739  1827.265435   
std       0.538288     0.084404     0.778405     0.677230   862.168977   
min       1.000000     0.000000     0.000000     1.000000   370.000000   
25%       1.000000     0.000000     0.000000     3.000000  1190.000000   
50%       1.500000     0.000000     0.000000     3.000000  1590.000000   
75%       2.000000     0.000000     0.000000     4.000000  2300.000000   
max       3.500000     1.000000     4.000000     5.000000  9410.000000   

       sqft_basement     yr_built  yr_renovated  
count    4600.000000  4600.000000   4600.000000  
mean      312.081522  1970.786304    808.608261  
std       464.137228    29.731848    979.414536  
min         0.000000  1900.000000      0.000000  
25%         0.000000  1951.000000      0.000000  
50%         0.000000  1976.000000      0.000000  
75%       610.000000  1997.000000   1999.000000  
max      4820.000000  2014.000000   2014.000000

In [5]:
df.shape

(4600, 18)

In [6]:
df["street"].unique()

array(['18810 Densmore Ave N', '709 W Blaine St',
       '26206-26214 143rd Ave SE', ..., '759 Ilwaco Pl NE',
       '5148 S Creston St', '18717 SE 258th St'],
      shape=(4525,), dtype=object)

In [7]:
df["country"].value_counts()

country
USA    4600
Name: count, dtype: int64

In [8]:
df["city"].value_counts()

city
Seattle                1573
Renton                  293
Bellevue                286
Redmond                 235
Kirkland                187
Issaquah                187
Kent                    185
Auburn                  176
Sammamish               175
Federal Way             148
Shoreline               123
Woodinville             115
Maple Valley             96
Mercer Island            86
Burien                   74
Snoqualmie               71
Kenmore                  66
Des Moines               58
North Bend               50
Covington                43
Duvall                   42
Lake Forest Park         36
Bothell                  33
Newcastle                33
Tukwila                  29
SeaTac                   29
Vashon                   29
Enumclaw                 28
Carnation                22
Normandy Park            18
Clyde Hill               11
Fall City                11
Medina                   11
Black Diamond             9
Ravensdale                7
Pacific        

In [9]:
# Ordinal or not?
# there exist an order or not?
df['view'].value_counts() # => kategoriskt värde

view
0    4140
2     205
3     116
4      70
1      69
Name: count, dtype: int64

In [10]:
import duckdb as db

query = db.query (
    """
    SELECT
        AVG(price) AS avg_price,
        condition
    FROM
        df
    GROUP BY
        2
    """
).df()

query

avg_price  condition
0  306633.333333          1
1  637041.322258          5
2  550111.516394          3
3  324373.750000          2
4  533647.286072          4

### Clean dataset

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           4600 non-null   object 
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64  
 5   sqft_lot       4600 non-null   int64  
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64  
 8   view           4600 non-null   int64  
 9   condition      4600 non-null   int64  
 10  sqft_above     4600 non-null   int64  
 11  sqft_basement  4600 non-null   int64  
 12  yr_built       4600 non-null   int64  
 13  yr_renovated   4600 non-null   int64  
 14  street         4600 non-null   object 
 15  city           4600 non-null   object 
 16  statezip       4600 non-null   object 
 17  country        4600 non-null   object 
dtypes: float

In [12]:
df_cleaned = df.drop(["country", "statezip", "street", "date", "city"], axis = "columns")

##### can also drop outliers => dvs de värden som sticker iväg väldigt "fel" jämfört med andra värden

In [13]:
df_cleaned

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0     3.130000e+05       3.0       1.50         1340      7912     1.5   
1     2.384000e+06       5.0       2.50         3650      9050     2.0   
2     3.420000e+05       3.0       2.00         1930     11947     1.0   
3     4.200000e+05       3.0       2.25         2000      8030     1.0   
4     5.500000e+05       4.0       2.50         1940     10500     1.0   
...            ...       ...        ...          ...       ...     ...   
4595  3.081667e+05       3.0       1.75         1510      6360     1.0   
4596  5.343333e+05       3.0       2.50         1460      7573     2.0   
4597  4.169042e+05       3.0       2.50         3010      7014     2.0   
4598  2.034000e+05       4.0       2.00         2090      6630     1.0   
4599  2.206000e+05       3.0       2.50         1490      8102     2.0   

      waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0              0     0          3        1340              0      1955   
1              0     4          5        3370            280      1921   
2              0     0          4        1930              0      1966   
3              0     0          4        1000           1000      1963   
4              0     0          4        1140            800      1976   
...          ...   ...        ...         ...            ...       ...   
4595           0     0          4        1510              0      1954   
4596           0     0          3        1460              0      1983   
4597           0     0          3        3010              0      2009   
4598           0     0          3        1070           1020      1974   
4599           0     0          4        1490              0      1990   

      yr_renovated  
0             2005  
1                0  
2                0  
3                0  
4             1992  
...            ...  
4595          1979  
4596          2009  
4597             0  
4598             0  
4599             0  

[4600 rows x 13 columns]

In [14]:
X, y = df_cleaned.drop("price", axis = 1), df_cleaned["price"]

X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0       3.0       1.50         1340      7912     1.5           0     0   
1       5.0       2.50         3650      9050     2.0           0     4   
2       3.0       2.00         1930     11947     1.0           0     0   
3       3.0       2.25         2000      8030     1.0           0     0   
4       4.0       2.50         1940     10500     1.0           0     0   

   condition  sqft_above  sqft_basement  yr_built  yr_renovated  
0          3        1340              0      1955          2005  
1          5        3370            280      1921             0  
2          4        1930              0      1966             0  
3          4        1000           1000      1963             0  
4          4        1140            800      1976          1992

### Dela upp datan i train | test

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42
)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3082, 12), (1518, 12), (3082,), (1518,))

### Skala datasetet

In [16]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler = StandardScaler().fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

scaled_X_train.min()

np.float64(-3.7457309137157586)

In [17]:
scaled_X_train.mean(), scaled_X_train.std()

(np.float64(-1.6267901295286201e-16), np.float64(1.0))

In [18]:
scaled_X_test.mean(), scaled_X_test.min()

(np.float64(0.010349104640750128), np.float64(-3.7457309137157586))

### Träna linjär regression

In [19]:
from sklearn.linear_model import LinearRegression, ElasticNet, RidgeCV #regualarisera 

model = LinearRegression()
model.fit(scaled_X_train, y_train)
y_pred = model.predict(scaled_X_test)

y_pred

array([ 296748.2583545 ,  318512.5986427 , 1067958.25109663, ...,
        647222.9627769 ,  465284.97110941,  839703.75324634],
      shape=(1518,))

In [20]:
def predict_house_prices(model):
    model.fit(scaled_X_train, y_train)
    y_pred = model.predict(scaled_X_test)

    return y_pred

predict_house_prices(LinearRegression())

array([ 296748.2583545 ,  318512.5986427 , 1067958.25109663, ...,
        647222.9627769 ,  465284.97110941,  839703.75324634],
      shape=(1518,))

In [21]:
y_test.values

array([ 544000.,       0., 1712500., ...,  450000.,  364000.,  403500.],
      shape=(1518,))

### Utvärdera

In [22]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.linear_model import ElasticNetCV
import numpy as np


def compute_metrics(y_test, y_pred):
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)

    return {
        "mean_absolute_error": mae,
        "mean_squared_error": mse,
        "root_mean_squared_error": rmse,
    }

y_pred_linear_regression = predict_house_prices(LinearRegression())
y_pred_ridge = predict_house_prices(RidgeCV())
y_pred_elasticnet = predict_house_prices(ElasticNetCV())


In [23]:

def compute_metrics(y_test, y_pred):
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    return mae, mse, rmse



In [24]:

compute_metrics(y_test, y_pred_ridge)

(191756.38824126765, 621240464122.7036, np.float64(788188.0893052772))

In [25]:

compute_metrics(y_test, y_pred_elasticnet)

(259611.936785628, 664290227641.4569, np.float64(815040.0159755697))